packages:
  - 'packages/*'

onlyBuiltDependencies:
  - bypp-format
  - esbuild
  - "@esbuild/win32-x64"

allowBuilds:
  "bypp-format@https://codeload.github.com/harpygg/bypp-format/tar.gz/6278cb988deb547240c617190c35dd3451d6b72a": true
  "esbuild@0.21.5": true
  "esbuild@0.27.4": true
  "@esbuild/win32-x64@0.21.5": true
  "@esbuild/win32-x64@0.27.4": true
  esbuild: set this to true or false
